i40e: fix build with icc
Since commit d798a94 ("mac vlan filter"),
ICC reports this error:
	lib/librte_pmd_i40e/i40e_ethdev.c(1763): error #188:
	enumerated type mixed with another type

Indeed, RTE_ETH_FILTER_NONE comes from enum rte_filter_type but
enum rte_filter_op is expected.

Signed-off-by: Thomas Monjalon <thomas.monjalon@6wind.com>